/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#107100",
        "tertiary": "#fdffb5",
        "surface-container-highest": "#353437",
        "on-surface-variant": "#baccb0",
        "surface-tint": "#2ae500",
        "secondary-container": "#00eefc",
        "on-secondary-container": "#00686f",
        "tertiary-fixed": "#e3ec00",
        "surface-dim": "#131315",
        "on-tertiary-container": "#616600",
        "inverse-primary": "#106e00",
        "outline-variant": "#3c4b35",
        "on-primary-fixed-variant": "#095300",
        "primary-container": "#39ff14",
        "background": "#131315",
        "on-tertiary": "#303300",
        "on-primary-fixed": "#022100",
        "surface-container-lowest": "#0e0e10",
        "on-secondary-fixed": "#002022",
        "primary-fixed-dim": "#2ae500",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#1c1d00",
        "error": "#ffb4ab",
        "outline": "#85967c",
        "surface-variant": "#353437",
        "on-background": "#e5e1e4",
        "primary": "#efffe3",
        "surface-container-high": "#2a2a2c",
        "surface": "#131315",
        "surface-container": "#201f21",
        "tertiary-fixed-dim": "#c7cf00",
        "tertiary-container": "#dee700",
        "on-secondary-fixed-variant": "#004f54",
        "secondary-fixed": "#7df4ff",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e5e1e4",
        "on-surface": "#e5e1e4",
        "secondary-fixed-dim": "#00dbe9",
        "on-secondary": "#00363a",
        "surface-bright": "#39393b",
        "on-primary": "#053900",
        "primary-fixed": "#79ff5b",
        "on-tertiary-fixed-variant": "#474a00",
        "secondary": "#d3fbff",
        "surface-container-low": "#1b1b1d",
        "inverse-on-surface": "#303032",
        "on-error": "#690005"
      },
      spacing: {
        "micro": "2px",
        "md": "8px",
        "sm": "4px",
        "margin-safe": "8px",
        "unit": "4px",
        "gutter": "4px",
        "lg": "12px"
      },
      fontFamily: {
        "data-xs": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "display-mono": ["JetBrains Mono", "monospace"],
        "data-md": ["JetBrains Mono", "monospace"],
        "data-lg": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}

